<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:activiti="http://activiti.org/bpmn"
             typeLanguage="http://www.w3.org/2001/XMLSchema"
             expressionLanguage="http://www.w3.org/1999/XPath" targetNamespace="http://www.activiti.org/test">

    <error id="unknownCustomer" errorCode="UNKNOWN_CUSTOMER"/>

    <process id="accept-customer-process">

        <startEvent id="start"/>
        <sequenceFlow sourceRef="start" targetRef="fetchData"/>
        <serviceTask id="fetchData"
                     activiti:class="com.blogspot.przybyszd.activitiinpractice.exceptions.CustomerFetcher"/>
        <sequenceFlow sourceRef="fetchData" targetRef="validateCustomer" id="autoFetch"/>

        <sequenceFlow sourceRef="fetchData" targetRef="manualFetchData" id="manualFetch"/>
        <userTask id="manualFetchData" name="manualFetchData"/>
        <sequenceFlow sourceRef="manualFetchData" targetRef="validateCustomer"/>

        <serviceTask id="validateCustomer" activiti:expression="${customerValidator.validate(fetchData)}"/>
        <sequenceFlow sourceRef="validateCustomer" targetRef="acceptCustomer"/>

        <serviceTask id="acceptCustomer" activiti:expression="${customerAccepter.accept()}"
                     activiti:resultVariable="customerAccepted"/>
        <sequenceFlow sourceRef="acceptCustomer" targetRef="end"/>


        <sequenceFlow sourceRef="start" targetRef="end"/>
        <endEvent id="end"/>

        <boundaryEvent attachedToRef="validateCustomer" id="unknownCustomerBoundary">
            <errorEventDefinition errorRef="unknownCustomer"/>
        </boundaryEvent>
        <sequenceFlow sourceRef="unknownCustomerBoundary" targetRef="rejectCustomer"/>
        <serviceTask id="rejectCustomer" activiti:expression="${customerRejecter.reject()}"
                     activiti:resultVariable="customerAccepted"/>
        <sequenceFlow sourceRef="rejectCustomer" targetRef="end"/>
    </process>

</definitions>
